pinger/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('pingerweb/')),
    url(r'^pingerweb/', include('pingerweb.urls')),
    url(r'^pingerservice/', include('pingerservice.urls')),
    url(r'^admin/', admin.site.urls),
]

pingerservice/urls.py
from django.conf.urls import url

from . import views

app_name = 'pingerservice'
urlpatterns = [
    url(r'^start_ping$', views.start_ping, name='start_ping'),
    # Chart api endpoints
    url(r'^api/chart/poolonline/(?P<pool_id>[0-9]+)/$',
        views.chart_data_pool_online,
        name='api_chart_data_pool_online'),
    url(r'^api/chart/pool/(?P<pool_id>[0-9]+)/$',
        views.chart_data_pool,
        name='api_chart_data_pool'),
    url(r'^api/chart/pool/'
        '(?P<pool_id>[0-9]+)'
        '/(?P<year>[0-9]+)'
        '/(?P<month>[0-9]+)'
        '/(?P<day>[0-9]+)/$',
        views.chart_data_pool_date,
        name='api_chart_data_pool_date'),
    # Export api endpoints
    url(r'^api/csv/pool/', views.generate_csv_data, name='api_csv_data'),
    # Data api endpoints
    url(r'^api/pools/$', views.pools, name='api_pools'),
]

pingerweb/urls.py
from django.conf.urls import url

from . import views

app_name = 'pingerweb'
urlpatterns = [
    # example: /pingerweb/
    url(r'^$', views.index, name='home'),
    # example: /pingerweb/pools
    url(r'^pools/$', views.pools, name='pools'),
    # example: /pingerweb/online
    url(r'^online/$', views.online, name='online'),
    # example: /pingerweb/consumption
    url(r'^consumption/$', views.consumption, name='consumption'),
    # example: /pingerweb/export
    url(r'^export/$', views.export, name='export'),
]

pingerweb/models.py
from django.db import models

# Create your models here.

pingerweb/views.py
from django.shortcuts import render
from tablib import Dataset

from datetime import datetime
import pingerservice.models as m
from pingerservice import tasks
from pingerservice.admin import IntervalResource


# Create your views here.
def index(request):
    return render(request, 'pingerweb/index.html')


def pools(request):
    return render(request, 'pingerweb/pools.html')


# IMPORT EXTRA
def add_day_reference(row):
    date_format = "%Y-%m-%d %H:%M:%S"

    computer_id = row[1]
    entry_date = datetime.strptime(row[2], date_format).date()
    entry_pc = m.Computer.objects.get(pk=computer_id)
    day = tasks.get_day_or_create(entry_pc, entry_date)
    return day.id


def online(request):
    import logging
    logger = logging.getLogger(__name__)

    if request.method == 'POST':
        import json
        from pytz import timezone, utc
        localtz = timezone('Europe/Berlin')
        date_format = "%Y-%m-%d %H:%M:%S"
        jsonfile = request.FILES['myfile']
        intervals = json.load(jsonfile)
        i_count = len(intervals)
        i_counter = 0
        for i in intervals:
            i_counter += 1
            logger.info("{} from {}".format(i_counter, i_count))
            comp_id = i.get('computer')
            start = i.get('start_time')
            end = i.get('end_time')
            start_time = localtz.localize(
                    datetime.strptime(start, date_format)).astimezone(utc)
            end_time = localtz.localize(datetime.strptime(
                end, date_format)).astimezone(utc)
            pc = m.Computer.objects.get(pk=comp_id)
            entry_date = start_time.date()
            end_date = end_time.date()
            i_day = tasks.get_day_or_create(pc, entry_date)
            i = m.Interval(day=i_day, start_time=start_time)
            i.save()
            inter = tasks.get_day_limited_interval(i, end_date)
            inter.end_time = end_time
            inter.save()
        #  dataset = Dataset()
        #  interval_resource = IntervalResource()
        #  new_intervals = request.FILES['myfile']
        #  dataset.load(new_intervals.read())
        #  dataset.append_col(add_day_reference, header='day')
        #  result = interval_resource.import_data(dataset, dry_run=True)

        #  if not result.has_errors():
        #    #  interval_resource.import_data(dataset, dry_run=False)

    return render(request, 'pingerweb/online.html')


def consumption(request):
    return render(request, 'pingerweb/consumption.html')


def export(request):
    return render(request, 'pingerweb/export.html')

pingerweb/templates/pingerweb/base.html
<!DOCTYPE html>
{% load static %}
{% load mdl_extras %}

{% url 'pingerweb:home' as home_url %}
{% url 'pingerweb:pools' as pools_url %}
{% url 'pingerweb:online' as online_url %}
{% url 'pingerweb:consumption' as consumption_url %}
{% url 'pingerweb:export' as export_url %}

<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <title>{% block title %}Projekt Pinger{% endblock title %}</title>
        <link rel="shortcut icon" href="{% static 'pingerweb/images/favicon.ico' %}" />
        <link rel="stylesheet" href="{% static 'pingerweb/css/material.min.css' %}">
        <script src="{% static 'pingerweb/css/material.min.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js" charset="utf-8"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" charset="utf-8"></script>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="{% static 'pingerweb/css/pinger.css' %}">
        <!-- HTML5 date picker -->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script charset="utf-8">
// API endpoints functions

/**
* Endpoint for getting chart data for online pcs of a pool
*
* @param poolId - pool to retrive data for
*/
var endpoint_chart_data_online_pcs = function(poolId) {
    return '{% url 'pingerservice:api_chart_data_pool_online' 0 %}'.replace(0, poolId)
}

/**
* Endpoint for getting chart data from today
*
* @param poolId - pool to retrive data for
*/
var endpoint_chart_data = function(poolId) {
    return '{% url 'pingerservice:api_chart_data_pool' 0 %}'.replace(0, poolId)
}

/**
* Endpoint for getting chart data of a given date
*
* @param poolId - pool to retreive data for
* @param year - year to use
* @param month - month to use
* @param day - day to use
*/
var endpoint_chart_date_url = function(poolId, year, month, day) {
    // resolve with placeholders so django can figure out the url
    var endpoint_chart_date = '{% url 'pingerservice:api_chart_data_pool_date' 0 1 2 3 %}'
    // remove placeholders
    endpoint_chart_date = endpoint_chart_date.replace('/0/1/2/3/', '')
    // add function parameters
    return endpoint_chart_date + "/" + poolId + "/" + year + "/" + month + "/" + day
}

/**
* Endpoint to get a list of all pools
*/
var endpoint_pools = function() {
    return '{% url 'pingerservice:api_pools' %}'
}
        </script>
        <script src="{% static 'pingerweb/scripts/pinger.js' %}"></script>
        {% block headextras %}{% endblock headextras %}
    </head>
    <body>
        <div class="mdl-layout mdl-js-layout mdl-layout--fixed-tabs mdl-layout--fixed-header mdl-layout--no-desktop-drawer-button">
            <header class="mdl-layout__header mdl-layout__header--waterfall pinger-header">
                {% block navigation %}
                <!-- Visible during scrolling -->
                <div class="mdl-layout__header-row">
                    <!-- Title -->
                    <img src="{% static 'pingerweb/images/pinger_banner.png'%}" alt="Pinger Logo" height="100%">
                    <span class="mdl-layout-title pinger-title">Project Pinger</span>
                </div>
                <!-- Hidden on scroll -->
                <nav class="mdl-layout__tab-bar mdl-js-ripple-effect pinger-tab-bar mdl-layout--large-screen-only">
                    <!-- Navigation -->
                    <a href="{{ home_url }}" class="mdl-layout__tab {% is_active request home_url %}">übersicht</a>
                    <a href="{{ pools_url }}" class="mdl-layout__tab {% is_active request pools_url %}">pools</a>
                    <a href="{{ online_url }}" class="mdl-layout__tab {% is_active request online_url %}">aktuell online</a>
                    <!-- <a href="{{ consumption_url }}" class="mdl-layout__tab {% is_active request consumption_url %}">verbrauch</a> -->
                    <a href="{{ export_url }}" class="mdl-layout__tab {% is_active request export_url %}">Export</a>
                </nav>
                {% endblock navigation%}
            </header>
            <div class="mdl-layout__drawer">
                <span class="mdl-layout-title">Project Pinger</span>
                <!-- Navigation -->
                <nav class="mdl-navigation">
                    <a href="{{ home_url }}" class="mdl-navigation__link {% is_active request home_url %}">Übersicht</a>
                    <a href="{{ pools_url }}"class="mdl-navigation__link {% is_active request pools_url %}">Pools</a>
                    <a href="{{ online_url }}" class="mdl-navigation__link {% is_active request online_url %}">Aktuell Online</a>
                    <!-- <a href="{{ consumption_url }}" class="mdl-navigation__link {% is_active request consumption_url %}">Verbrauch</a> -->
                    <a href="{{ export_url }}" class="mdl-navigation__link {% is_active request export_url %}">Export</a>
                </nav>
            </div>
            <main class="mdl-layout__content">
            <div class="mdl-grid">
                {% block content %}
                {% endblock content %}
            </div>
            </main>
        </div>
    </body>
</html>

pingerweb/templates/pingerweb/consumption.html
{% extends "pingerweb/base.html" %}

{% block title %}Verbrauch - {{ block.super }}{% endblock title %}

{% block content %}
Hallo Verbrauch
{% endblock content %}

pingerweb/templates/pingerweb/export.html
{% extends "pingerweb/base.html" %}

{% block title %}Export - {{ block.super }}{% endblock title %}

{% block content %}
<div class="mdl-cell mdl-cell--4-col mdl-cell--6-col-tablet mdl-cell--8-col-desktop mdl-cell--1-offset-tablet mdl-cell--2-offset-desktop">
    <!-- Card which holds the Export settings and room selector -->
    <div class="pinger-card mdl-card mdl-shadow--2dp">
        <!-- form to choose settings -->
        <div class="mdl-card__title">
            <form id="export-form" action="{% url 'pingerservice:api_csv_data' %}" method="get" accept-charset="utf-8">
                <div class="mdl-card__title">
                    <h4 class="mdl-card__title-text">Select Pools</h4>
                </div>

                <ul id="pool_menu" class="mdl-list">
                </ul>

                <div class="mdl-layout-spacer"></div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="date" name="start_date" id="date_start_selection">
                    <label class="mdl-textfield__label" for="date_start_selection">Von</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="date" name="end_date" id="date_end_selection">
                    <label class="mdl-textfield__label" for="date_end_selection">Bis</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label is-dirty">
                    <select class="mdl-textfield__input pool-select" id="format_selection" name="output_format">
                        <option value="unix">LibreOffice</option>
                        <option value="excel">Microsoft Excel</option>
                    </select>
                    <label class="mdl-textfield__label" for="format_selection">Format</label>
                </div>
            </form>
        </div>
        <!-- canvas to display chart -->
        <div class="mdl-card__actions mdl-card--border">
            <!-- Flat button with ripple -->
            <button class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--primary" form="export-form">Export</button>
        </div>
    </div>
</div>
<script>

addDatepickerToTextInput('date_start_selection')
addDatepickerToTextInput('date_end_selection')

// load pool list when page is ready
$(window).on('load', function() {
    getPoolListData(function(pools){
        // fill pool selection list 
        setPoolListMdl('pool_menu', pools)
    });
});
</script>
{% endblock content %}

pingerweb/templates/pingerweb/index.html
{% extends "pingerweb/base.html" %}

{% block title %}Home - {{ block.super }}{% endblock title %}

{% block content %}

<div class="mdl-cell mdl-cell--4-col mdl-cell--6-col-desktop mdl-cell--2-offset-tablet mdl-cell--3-offset-desktop">
    <h3>Project Pinger</h3>
    <p>
    Das Projekt HFT Pinger ist im Rahmen des Moduls Pervasive Computing/Ubiquitous Computing entstanden.
    Ziel des Projekts ist es eine Übersicht über die Rechnernutzung an der HFT zu bekommen.
    <br>
    Der HFT-PC-Finder hilft Ihnen dabei eine Rechnerraum zu finden der ihren aktuellen Suchkriterien entspricht. Für Android Geräte kann diese auch als App installiert werden.
    <br>
    <br>

    <a href='HFTPCFinder.apk'> Download HFT-PC-Finder.apk (Version: 2.0.1, BUILD Date: 25.11.2015, OpenConnect required) for Android </a>
    <br>
    <br>
    Diese Website ermöglicht es Ihnen über diverse Graphen, Informationen über die Rechnernutzung einzusehen.

    </p>
    <br>
    <br>
    <p>
    Idee und ursprüngliche Betreuung: Prof. S. Knauth, M. Schulz-Merkel.
    </p>
    <br/>
    <p>
    Dieses Projekt wird entwickelt von Arthur Grigorjan und Yasin Abdelmonem.
    </p>
    <br/>
    <p>
    Das Projekt wird technisch momentan von Alexander Dobler (alexander.dobler@hft-stuttgart.de) betreut.
    </p>
</div>

{% endblock content %}

pingerweb/templates/pingerweb/online.html
{% extends "pingerweb/base.html" %}

{% block title %}Online - {{ block.super }}{% endblock title %}

{% block content %}

<div class="mdl-cell mdl-cell--4-col mdl-cell--6-col-tablet mdl-cell--8-col-desktop mdl-cell--1-offset-tablet mdl-cell--2-offset-desktop">
    <div class="pinger-chart-card mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title">
            <!-- drop down menu to choose pool -->
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label is-dirty">
                <select class="mdl-textfield__input pool-select" id="pool_selection">
                </select>
                <label class="mdl-textfield__label" for="pool_selection">Pool</label>
            </div>
            <div class="mdl-layout-spacer"></div>
	    <!--
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="myfile">
                <button type="submit">Upload</button>
            </form>
	    -->
        </div>
        <!-- canvas to display chart -->
        <div class="mdl-card__actions mdl-card--border pinger-chart-container">
            <canvas id="poolChart" height="300" class="pinger-chart-canvas" ></canvas>
        </div>
    </div>
</div>

<script>
// DOM Elements
var poolSelectionElem = document.getElementById("pool_selection");

// chart element
var pingerChart;

// function to generate a pie chart
function createPieChart (domId, chartData){
    var pingChartElem = document.getElementById(domId).getContext('2d')
    
    if(pingerChart){
        // reset the chart if already visible
        pingerChart.destroy();
    }

    pingerChart = new Chart(pingChartElem, {
        type: 'doughnut',
        data: {
            datasets: [{
                    data: [chartData.online, chartData.offline],
                    backgroundColor: ["#e37151cc", "#d3d3d3aa"],
                    hoverBackgroundColor: ["#e37151ee", "#d3d3d3cc"]
                }],
        
            // These labels appear in the legend and in the tooltips when hovering different arcs
            labels: [
                    'Online',
                    'Offline'
                ]
        },
        options: {
            title: {
                display: true,
                text: 'Pool: '+chartData.room_no,
                fontSize: 16
            },
            responsive: true,
            maintainAspectRatio: false,
            legend: {
                display: true,
                position: "top"
            }
        }
    });
}

// call chart creation when page is ready
$(window).on('load', function() {
    getPoolListData(function(pools){
        // fill pool selection drop down and call chart creation on change
        setPoolList('pool_selection', pools, function(pool){
            // get newly selected pool
            var poolNo = $( '#pool_selection' ).val();

            // load pool online data and call chart creation on success
            getCurrentlyOnline(poolNo, function(chartData){
                createPieChart('poolChart', chartData);
            })
        });


        // get first pool 
        firstPool = pools[0].pk;
        // preload initial chart with first pools data
        getCurrentlyOnline(firstPool, function(chartData){
            createPieChart('poolChart', chartData);
        })

    });
});
</script>
{% endblock content %}

pingerweb/templates/pingerweb/pools.html
{% extends "pingerweb/base.html" %}

{% block title %}Pools - {{ block.super }}{% endblock title %}

{% block content %}
<div class="mdl-cell mdl-cell--4-col mdl-cell--6-col-tablet mdl-cell--8-col-desktop mdl-cell--1-offset-tablet mdl-cell--2-offset-desktop">
    <!-- Card which holds the chart and room selector -->
    <div class="pinger-chart-card mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title">
            <!-- drop down menu to choose pool -->
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label is-dirty">
                <select class="mdl-textfield__input pool-select" id="pool_selection">
                </select>
                <label class="mdl-textfield__label" for="pool_selection">Pool</label>
            </div>
            <div class="mdl-layout-spacer"></div>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <input class="mdl-textfield__input" type="date" id="date_selection">
                <label class="mdl-textfield__label" for="date_selection">Date</label>
            </div>
        </div>
        <!-- canvas to display chart -->
        <div class="mdl-card__actions mdl-card--border pinger-chart-container">
            <canvas id="poolChart" height="300" class="pinger-chart-canvas" ></canvas>
        </div>
    </div>
</div>

<script>
// DOM Elements
var pingChartElem = document.getElementById("poolChart").getContext('2d')
var poolSelectionElem = document.getElementById("pool_selection")
var dateSelectionElem = document.getElementById("date_selection")

// JS variables
var labels = []
var poolData = []
var room_no = []
var pingerChart;

// function to create a chart for values in datepicker and room list
function createChart(){
    var dateObject;
    // if date input is not supported use jquery date picker, else native date
    if ($('#date_selection').get(0).type != 'date'){
        dateObject = $( '#date_selection' ).datepicker('getDate');
    } else {
        dateObject = $( '#date_selection' ).get(0).valueAsDate;
    }
    var roomNo = $( '#pool_selection' ).val();
    getChartDateData(roomNo, dateObject.getFullYear(), dateObject.getMonth()+1, dateObject.getDate(), setChart);
}

// setup datepicker, add select listener and set to current date
addDatepickerToTextInput('date_selection', createChart)

function resetChart(){
    pingerChart.destroy()
}

function setChart(chartData){
    if(pingerChart){
        // reset the chart if already visible
        resetChart();
    }
    pingerChart = new Chart(pingChartElem, {
        type: 'line',
        data: {
            labels: chartData.labels,
            datasets: [{
                label: chartData.room_no,
                data: chartData.poolData,
                backgroundColor: "#e3715155",
                borderColor: "#d05e3e",
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            legend: {
                display: true,
                position: "top"
            },
            scales: {
                yAxes: [{
                    scaleLabel: {
                        display: true,
                        labelString: "Anzahl der Rechner",
                    },
                    ticks: {
                        suggestedMin: 0,
                        stepsize: 1,
                    },
                }],
            },
            ticks: {
                min: 0,
                beginAtZero: true
            }
        }
    })
}

// call chart creation when page is ready
$(window).on('load', function() {
    getPoolListData(function(pools){
        // fill pool selection drop down, on change update chart
        setPoolList('pool_selection', pools, createChart)
        createChart()
    });
});

</script>
{% endblock content %}